server:
  port: 8099

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      api-host: https://api.openai.com/
      api-key: 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
      auth-token: xxx

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml


# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    appid: wxd8a91a853a87256d
    originalid: gh_0a479e03adb9
    token: cuhk
