server:
  port: 80

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: https://itedus.cn

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      api-host: https://api.openai.com/
      api-key: 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
      auth-token: xxx

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
